name: CI Pipeline

on: [push]

env:
  PASSWORD: ${{ secrets.APP_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: python app.py

      - run: echo $PASSWORD
